//
// Created by Iris on 2021/5/1.
//

#ifndef COMPUTE_MODULE_COMPUTE_CONSTANT_H
#define COMPUTE_MODULE_COMPUTE_CONSTANT_H

#include "cfloat"

#define DOUBLE_NUMBER_INIT_VALUE 0.00
#define DOUBLE_NUMBER_FACTOR_VALUE 1.00
#define DOUBLE_NUMBER_ERROR_VALUE -1.00

#define SQUARE_INDEX_NUMBER 2

#define  DOUBLE_MAX_VALUE DBL_MAX;
#define  DOUBLE_MIN_VALUE DBL_MIN;
#endif //COMPUTE_MODULE_COMPUTE_CONSTANT_H
